### PR TITLE
Change token length + index

### PR DESCRIPTION
**Pull request by kevyworks**
255 should be enough for most cases for encrypted token.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @kevmt! 👋 

Thanks for your PR. ❤️ 
Could you please elaborate on why we need to change the length of the field to 255 and add an index to it for the default API template?

**Comment by kevyworks** [comment]
Hi, I added index because from adonis code tokens are used to getAllTokens and query to find specific token. Adding also 255 as varchar where some tokens are longer than the default length provided.

**Review by RomainLanz — APPROVED** [review]

**Review by thetutlage — APPROVED** [review]

**Comment by thetutlage** [comment]
@kevmt It will be nice if you can create a PR for following too.

https://github.com/adonisjs/adonis-fullstack-app/blob/develop/database/migrations/1503248427886_token.js

and here
https://github.com/adonisjs/adonis-auth/blob/develop/templates/TokenSchema.js

**Comment by kevyworks** [comment]
@thetutlage Hi there! Submitted PR's as requested.

**Pull request merged**
